# Generated by Django 3.1.7 on 2024-04-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derecho_predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha con la cual se creo el registro', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha con la cual se modifico el objeto', verbose_name='modified at')),
                ('fraccion_derecho', models.FloatField(null=True)),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
                ('fuente_administrativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catastro.fuenteadmon', db_column='id_registro')),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.interesado')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.lcdcpredio', db_column='id_predio')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
