# Generated by Django 3.1.7 on 2024-04-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_derecho_predio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derecho_predio',
            name='predio',
            field=models.ForeignKey(db_column='id_predio', on_delete=django.db.models.deletion.CASCADE, to='catastro.lcdcpredio'),
        ),
    ]
