# Generated by Django 3.1.7 on 2024-04-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_auto_20240425_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'historia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
